export const FETCHING_POSTS = 'FETCHING_POSTS';
export const FETCHING_POSTS_SUCCESS = 'FETCHING_POSTS_SUCCESS';
export const FETCHING_POSTS_FAILURE = 'FETCHING_POSTS_FAILURE';
export const CLEAR_POSTS = 'CLEAR_POSTS';

export const FETCHING_COMPANY = 'FETCHING_COMPANY';
export const FETCHING_COMPANY_SUCCESS = 'FETCHING_COMPANY_SUCCESS';

